import type { Request, Response } from 'express';
import { query } from '../config/database.js';
import { empresaDe } from '../middleware/authenticate.js';
import * as encomendas from '../repositories/orders.repository.js';
import type { OrderStatus } from '../domain/orderStatus.js';
import { HOJE_LOCAL, INICIO_DE_HOJE, comoInstante } from '../domain/tempo.js';

/**
 * The dashboard is one round trip of aggregates plus a short recent list. Counting
 * in the database instead of loading rows and counting in Node keeps this cheap as
 * the table grows.
 */
export const resumo = async (req: Request, res: Response): Promise<void> => {
  const companyId = empresaDe(req);

  const kpis = await query<{
    orders_today: string;
    in_delivery: string;
    delivered: string;
    failed: string;
    late: string;
  }>(
    `SELECT
       count(*) FILTER (WHERE created_at >= ${INICIO_DE_HOJE}) AS orders_today,
       count(*) FILTER (WHERE status IN ('ATRIBUIDO', 'RECOLHIDO', 'EM_ENTREGA')) AS in_delivery,
       count(*) FILTER (WHERE status = 'ENTREGUE') AS delivered,
       count(*) FILTER (WHERE status = 'FALHA_ENTREGA') AS failed,
       count(*) FILTER (
         WHERE expected_delivery_at IS NOT NULL
           AND expected_delivery_at < now()
           AND status NOT IN ('ENTREGUE', 'CANCELADO', 'DEVOLVIDO')
       ) AS late
     FROM orders
     WHERE company_id = $1`,
    [companyId],
  );

  const porEstado = await query<{ status: OrderStatus; count: string }>(
    `SELECT status, count(*) AS count
       FROM orders
      WHERE company_id = $1
      GROUP BY status`,
    [companyId],
  );

  // A fixed 14-day window, generated by the database so days with no orders still
  // appear as zero instead of leaving a gap in the chart. The days are Luanda days;
  // the boundaries they are compared against are the instants those days began.
  const porDia = await query<{ day: string; count: string }>(
    `WITH dias AS (
       SELECT generate_series(${HOJE_LOCAL} - interval '13 days',
                              ${HOJE_LOCAL},
                              interval '1 day') AS dia
     )
     SELECT to_char(dias.dia, 'YYYY-MM-DD') AS day,
            count(o.id) AS count
       FROM dias
       LEFT JOIN orders o
              ON o.company_id = $1
             AND o.created_at >= ${comoInstante('dias.dia')}
             AND o.created_at < ${comoInstante('dias.dia + interval \'1 day\'')}
      GROUP BY dias.dia
      ORDER BY dias.dia`,
    [companyId],
  );

  const motoristas = await query<{ total: string }>(
    `SELECT count(*) AS total FROM drivers
      WHERE company_id = $1 AND is_active AND status IN ('DISPONIVEL', 'EM_ENTREGA')`,
    [companyId],
  );

  const recentes = await encomendas.listar(companyId, { page: 1, pageSize: 8 });

  res.json({
    ordersToday: Number(kpis.rows[0]?.orders_today ?? 0),
    inDelivery: Number(kpis.rows[0]?.in_delivery ?? 0),
    delivered: Number(kpis.rows[0]?.delivered ?? 0),
    failed: Number(kpis.rows[0]?.failed ?? 0),
    late: Number(kpis.rows[0]?.late ?? 0),
    activeDrivers: Number(motoristas.rows[0]?.total ?? 0),
    byStatus: porEstado.rows.map((linha) => ({ status: linha.status, count: Number(linha.count) })),
    perDay: porDia.rows.map((linha) => ({ day: linha.day, count: Number(linha.count) })),
    recent: recentes.linhas.map(encomendas.paraResumo),
  });
};
